### ISSUE TITLE
Upgrade Next.js to 11.x

### ISSUE THREAD

**Issue by swilgosz** [swilgosz/hanamimastery#11]
### Overview

Upgrade the next.js and related packages to the latest version, while keeping the project functional.

**Refer to**: https://nextjs.org/docs/upgrading

**List of features:**
- Social sharing
- Discuss comments
- Episodes listing https://hanamimastery.com/
- Articles listing https://hanamimastery.com/stray
- RSS feed  https://hanamimastery.com/feed
- Youtube Iframe previews
- Github sponsors iframe
- Newsletter form iframe
- HTML Metadata generation

**Comment by adamszwaba** [comment]
Done in recent commit.
