### ISSUE TITLE
UI issues after Next update

### ISSUE THREAD

**Issue by swilgosz** [swilgosz/hanamimastery#13]
### Overview.

There is an issue in the UI, where container's top-margin (above article's wrapper and sidebar wrapper) is reduced.

Screenshots.

![image](https://user-images.githubusercontent.com/8088317/127237783-1f6345ab-131e-493a-8eea-9332ec0765c5.png)

![image](https://user-images.githubusercontent.com/8088317/127237809-daa6401a-8fd4-4e5f-b48f-90f5f7525a86.png)

### Possible source of the problem

When we open the console, we can easily see that several JS scripts raised errors. Possibly those result in UI being broken, as iframes (sharing buttons, GitHub sponsors, optinmonster.js) - cannot be fully loaded.

![image](https://user-images.githubusercontent.com/8088317/127237926-d1390387-ab9d-4f82-8b2c-24e330f1c531.png)

**Acceptance criteria**

Fix the Errors appearing in the dev tools console 

- `Failed to find player`
- `Unexpected token u in JSON at position 0`

**Comment by adamszwaba** [comment]
Like I mentioned: I failed to recreate the issue on my laptop and PC, on multiple browsers. Is it still persistent? Can you pin point a specific browser?

**Comment by swilgosz** [comment]
@adamszwaba I confirmed, this is because of my browser addons, thanks for pointing this out!
